name: Release system-metrics

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              if: github.event_name != 'pull_request'
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: yanshuy/system-metrics
                  tags: |
                      type=raw,value=latest
                      type=sha,format=short
                      type=semver,pattern={{version}}
                      type=semver,pattern={{major}}.{{minor}}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: ${{ github.event_name != 'pull_request' }}
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}

    deploy:
        needs: build
        runs-on: ubuntu-latest
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        steps:
            - name: Trigger render deploy
              if: success()
              run: |
                  echo "Triggering Render deployment..."
                  response=$(curl -s -w "%{http_code}" -X POST ${{ secrets.RENDER_DEPLOY_HOOK }})
                  http_code="${response: -3}"
                  if [ "$http_code" -eq 200 ] || [ "$http_code" -eq 201 ]; then
                    echo "✅ Deployment triggered successfully (HTTP $http_code)"
                  else
                    echo "❌ Deployment failed (HTTP $http_code)"
                    exit 1
                  fi
